### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by pcouas** [thiagorossener/aloisioimoveis#2]
Hi

I am on windows10 with python 3.9 i have tried to install your project without succes
>py -m pip install -r requirements-dev.txt

ERROR: Command errored out with exit status 1: 'D:\zpoubelle\realestate\p1\aloisioimoveis-master\aloisioimoveis\.aloisioimoveis\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\COUAS\\AppData\\Local\\Temp\\pip-install-12awfw_v\\psycopg2\\setup.py'"'"'; __file__='"'"'C:\\Users\\u1\\AppData\\Local\\Temp\\pip-install-12awfw_v\\psycopg2\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\u1\AppData\Local\Temp\pip-record-ued4ogkj\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\zpoubelle\realestate\p1\aloisioimoveis-master\aloisioimoveis\.aloisioimoveis\include\site\python3.9\psycopg2' Check the logs for full command output.

What is my error regards ?

**Comment by thiagorossener** [comment]
Hi @pcouas, unfortunately, this project is no longer supported.

I'm sorry, but I'm not updated with the latest Django and Python versions, so I can't help you more.

My guess is that your error is a version incompatibility.
